name=MyNonBlockingDelay
version=1.0.0
author=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
maintainer=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
sentence=A simple library to handle a non-blocking delay.
paragraph=This library makes it easy to handle a non-blocking delay.
category=Device Control
url=https://github.com/tonprofil/NonBlockingDelay
architectures=*
includes=NonBlockingDelay.h
